# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OiOSyxfJJYjUrFI-8CyR1k0BknLwrVUu
"""



with open('/content/linear-regression.pysb', 'r') as f:
    file_content = f.read()

print(file_content)

import json

# Assuming file_content holds the string from the .pysb file
notebook_data = json.loads(file_content)

# Create a list to hold the new cells to be generated
cells_to_generate = []

for cell in notebook_data['cells']:
    cell_type = cell['type']
    cell_content = cell['content']

    # For Python cells, we need to ensure the content is properly formatted
    if cell_type == 'python':
        # Python cells in .pysb files typically have content as a single string
        # or a list of strings, so we join if it's a list.
        if isinstance(cell_content, list):
            code = '\n'.join(cell_content)
        else:
            code = cell_content
        cells_to_generate.append({'cell_type': 'python', 'code': code})
    elif cell_type == 'markdown':
        # Markdown cells in .pysb files also have content as a single string
        # or a list of strings, so we join if it's a list.
        if isinstance(cell_content, list):
            markdown = '\n'.join(cell_content)
        else:
            markdown = cell_content
        cells_to_generate.append({'cell_type': 'markdown', 'code': markdown})

# This print statement is for verification; the actual generation will happen
# when the agent returns the `generate_cells` command with the appropriate codeblocks.
print(f"Prepared {len(cells_to_generate)} cells for generation.")

"""# Regression

*Supervised* machine learning techniques involve training a model to operate on a set of *features* and predict a *label* using a dataset that includes some already-known label values. The training process *fits* the features to the known labels to define a general function that can be applied to new features for which the labels are unknown, and predict them. You can think of this function like this, in which ***y*** represents the label we want to predict and ***x*** represents the features the model uses to predict it:

> f(x)=y

In most cases, *x* is actually a *vector* that consists of multiple feature values, so to be a little more precise, the function could be expressed like this:

> f([x_1, x_2, x_3, ...]) = y

The goal of training the model is to find a function that performs some kind of calculation to the *x* values that produces the result *y*. We do this by applying a machine learning *algorithm* that tries to fit the *x* values to a calculation that produces *y* reasonably accurately for all of the cases in the training dataset.

There are many machine learning algorithms for supervised learning, and we can broadly divide them into two types:

- **_Regression_ algorithms**: Algorithms that predict a *y* value that is a numeric value, such as the price of a house or the number of sales transactions.
- **_Classification_ algorithms**: Algorithms that predict to which category, or *class*, an observation belongs. The *y* value in a classification model is a vector of probability values between 0 and 1, one for each class, indicating the probability of the observation belonging to each class.

In this notebook, we'll focus on *regression*, using an example based on a real study in which data for a bicycle sharing scheme was collected and used to predict the number of rentals based on seasonality and weather conditions. We'll use a simplified version of the dataset from that study.

## Load the data

The first step in any machine-learning project is to explore the data that you'll use to train a model. The goal of this exploration is to try to understand the relationships between its attributes; in particular, any apparent correlation between the *features* and the *label* your model will try to predict. This may require some work to detect and fix issues in the data (such as dealing with missing values, errors, or outlier values), deriving new feature columns by transforming or combining existing features (a process known as *feature engineering*), *normalizing* numeric features (values you can measure or count) so they're on a similar scale, and *encoding* categorical features (values that represent discrete categories) as numeric indicators.

1. Download [daily-bike-share.csv](https://raw.githubusercontent.com/MicrosoftLearning/mslearn-ml-basics/refs/heads/main/Labfiles/data/daily-bike-share.csv){:target="_blank"} in a new browser tab, and save it on your local disk.
2. Then use the **Upload Data** button at the top of this notebook to upload it.
3. Run the next cell by clicking the **&#9658; Run** button to load the data and view the first few rows.

> **Citation**: The data we used in this exercise is derived from [Capital Bikeshare](https://www.capitalbikeshare.com/system-data) and it's used in accordance with the published [license agreement](https://www.capitalbikeshare.com/data-license-agreement).

"""

import pandas as pd

# load the training dataset
bike_data = pd.read_csv('https://raw.githubusercontent.com/MicrosoftLearning/mslearn-ml-basics/refs/heads/main/Labfiles/data/daily-bike-share.csv')
print(bike_data.head())

"""The data consists of the following columns:

- **instant**: A unique row identifier
- **dteday**: The date on which the data was observed; in this case, the data was collected daily, so there's one row per date.
- **season**: A categorical indicator for the season (1:spring, 2:summer, 3:fall, 4:winter)
- **yr**: The year of the data (0:2011, 1:2012)
- **mnth**: The calendar month (1-12)
- **holiday**: A binary value indicating whether the day was a public holiday
- **weekday**: The day of the week (0:Sunday, 1:Monday, etc.)
- **workingday**: A binary value indicating whether the day was a working day (not a weekend or holiday)
- **weathersit**: A categorical indicator for the weather situation (1:clear, 2:mist/cloud, 3:light rain/snow, 4:heavy rain/snow)
- **temp**: The temperature in Celsius (normalized)
- **atemp**: The "feels-like" temperature in Celsius (normalized)
- **hum**: The humidity level (normalized)
- **windspeed**: The windspeed (normalized)
- **casual**: The number of rentals by casual users
- **registered**: The number of rentals by registered users
- **rentals**: The total number of rental bikes (casual + registered)

The `rentals` column is the label our model will be trained to predict. The other columns are potential features.

Note that `dteday` is the date of the observation, and in a real-world scenario, you'd typically split data based on time to avoid "data leakage" (where your model is influenced by data from the future). In this case, we're not using date as a predictive feature, so we'll treat each day as an independent observation, and we'll randomize the way we split the data into training and validation datasets. We'll also simplify the dataset by dropping the `instant`, `casual`, and `registered` columns.
"""

bike_data['dteday'] = pd.to_datetime(bike_data['dteday'])
print(bike_data.head())
# Drop unneeded columns
bike_data = bike_data.drop(['instant', 'dteday', 'yr'], axis=1)

# Show the first 5 rows
print(bike_data.head())

"""Now let's explore the distribution of the numeric features.

"""

import matplotlib.pyplot as plt

# Get the label column
label = bike_data['rentals']

# Create a figure for 2 subplots (temperature, humidity, windspeed)
fig, axs = plt.subplots(1, 3, figsize=(15, 5))

# Plot the label
axs[0].hist(bike_data['temp'])
axs[0].set_ylabel('Frequency')
axs[0].set_xlabel('Temperature')
axs[0].set_title('Distribution of Temperature')

# Plot the humidity
axs[1].hist(bike_data['hum'])
axs[1].set_ylabel('Frequency')
axs[1].set_xlabel('Humidity')
axs[1].set_title('Distribution of Humidity')

# Plot the windspeed
axs[2].hist(bike_data['windspeed'])
axs[2].set_ylabel('Frequency')
axs[2].set_xlabel('Windspeed')
axs[2].set_title('Distribution of Windspeed')

# Add a title to the Figure
fig.suptitle('Distributions of Numeric Features')

plt.tight_layout()
plt.show()

"""The distributions of `temp`, `hum`, and `windspeed` all appear to be approximately normal, with most values near the mean and fewer values towards the extremes. This is a good indication that these features could be useful in predicting `rentals`.

The `rentals` distribution is positively skewed, meaning there are more days with lower rental counts and fewer days with very high rental counts. This kind of distribution is common for count data, and it might be helpful to transform the label to make its distribution more symmetric if we were using a model that assumes normally distributed residuals (errors).

Now let's look at the correlation between the numeric features and the label.
"""

# Show the label distribution
fig = plt.figure(figsize=(9, 6))
plt.hist(label)
plt.xlabel('Rentals')
plt.ylabel('Frequency')
plt.title('Distribution of Rentals')
plt.show()

# Show the correlation between the numeric features and the label
for col in ['temp', 'hum', 'windspeed']:
    fig = plt.figure(figsize=(9, 6))
    plt.scatter(x=bike_data[col], y=label)
    plt.xlabel(col)
    plt.ylabel('Rentals')
    plt.title(f'Rentals vs {col}')
    plt.show()

"""The plots show some correlation between the numeric features and rentals. `temp` and `atemp` show a clear positive correlation, while `hum` and `windspeed` show a slight negative correlation. These relationships suggest that these features could be good predictors for `rentals`.

Now let's look at the categorical features.

"""

for col in ['season', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit']:
    fig = plt.figure(figsize=(9, 6))

    # Get unique categories for the current column and sort them for consistent plotting
    categories = bike_data[col].unique()
    categories.sort()

    # Prepare a list of rental data for each category
    data_to_plot = [bike_data[bike_data[col] == cat]['rentals'] for cat in categories]

    # Create the box plot
    plt.boxplot(data_to_plot)

    # Set labels and title
    plt.xlabel(col)
    plt.ylabel('Rentals')
    plt.title(f'Rentals by {col}')

    # Set x-axis ticks and labels to correspond to the categories
    plt.xticks(ticks=range(1, len(categories) + 1), labels=categories)

    plt.show()

"""The box plots show clear differences in the distribution of rentals across the categories for `season`, `mnth`, `holiday`, `weekday`, `workingday`, and `weathersit`. This indicates that these categorical features are also good candidates for predicting rentals.

We've performed some basic data exploration, and we've confirmed that the features in the dataset seem to have predictive power. Now we're ready to prepare the data for machine learning.

## Prepare the data

Before we can train a model, we need to preprocess the data. This involves:

- Separating the features from the label, and creating a training set and a test set.
- Normalizing the numeric features so they're on a similar scale.
- One-hot encoding the categorical features so they can be used in the model.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Separate features and labels
X, y = bike_data.drop('rentals', axis=1), bike_data['rentals']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Identify numeric and categorical features
numeric_features = ['temp', 'hum', 'windspeed']
categorical_features = ['season', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit']

# Create preprocessing pipelines for numeric and categorical features
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Combine preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Apply preprocessing to training and testing data
X_train_preprocessed = preprocessor.fit_transform(X_train)
X_test_preprocessed = preprocessor.transform(X_test)

print("Preprocessing complete.")
print(f"Preprocessed training data shape: {X_train_preprocessed.shape}")
print(f"Preprocessed testing data shape: {X_test_preprocessed.shape}")

"""## Train a model

Now that the data is prepared, we can train a regression model. We'll use a `LinearRegression` model from `sklearn`.
"""

from sklearn.linear_model import LinearRegression

# Train a Linear Regression model
model = LinearRegression()
model.fit(X_train_preprocessed, y_train)

print("Model trained.")

"""## Evaluate the model

Now that the model is trained, we can evaluate its performance on the test set. We'll use the `r2_score` and `mean_squared_error` metrics to assess the model's accuracy.
"""

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Make predictions on the test set
y_pred = model.predict(X_test_preprocessed)

# Calculate metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R2 Score: {r2:.2f}")

# Plot predicted vs actual
fig = plt.figure(figsize=(9, 6))
plt.scatter(y_test, y_pred)
plt.xlabel('Actual Rentals')
plt.ylabel('Predicted Rentals')
plt.title('Actual vs Predicted Rentals')
plt.show()

"""# Task
Fix the `ValueError` and `NameError` in cell `8088c45a` by changing `pd.to_datetime(bike_data)` to `pd.to_datetime(bike_data['dteday'])` and updating the column name to be dropped from 'year' to 'yr', then rerun cell `8088c45a` and all subsequent cells (`c85c6abf`, `7b1b5268`, `2e888073`, `76f3b978`, `099f14d4`, `2203a929`, `336657cb`).

## Fix ValueError and NameError in cell 8088c45a

### Subtask:
Modify cell `8088c45a` to correctly convert the 'dteday' column to datetime objects using `pd.to_datetime(bike_data['dteday'])` and change the column name to be dropped from 'year' to 'yr'. This will resolve the `ValueError` and ensure the `bike_data` DataFrame is properly structured for subsequent operations.

**Reasoning**:
The subtask requires modifying cell `8088c45a` to correct the `ValueError` by specifying the 'dteday' column for datetime conversion and changing 'year' to 'yr' in the columns to be dropped, which will resolve all previous errors.
"""

bike_data['dteday'] = pd.to_datetime(bike_data['dteday'])
print(bike_data.head())
# Drop unneeded columns
bike_data = bike_data.drop(['instant', 'dteday', 'yr', 'casual', 'registered'], axis=1)

# Show the first 5 rows
print(bike_data.head())

"""**Reasoning**:
The previous execution of cell `c66d91e4` (originally `8088c45a`) resulted in a `KeyError` because the columns 'casual' and 'registered' were not found in the DataFrame, even though they were part of the list to be dropped. This indicates that these columns are not present in the loaded `bike_data`. The fix involves removing 'casual' and 'registered' from the list of columns to be dropped, along with correcting the 'dteday' conversion and changing 'year' to 'yr' as per the original instruction.


"""

bike_data['dteday'] = pd.to_datetime(bike_data['dteday'])
print(bike_data.head())
# Drop unneeded columns
bike_data = bike_data.drop(['instant', 'dteday', 'yr'], axis=1)

# Show the first 5 rows
print(bike_data.head())

"""**Reasoning**:
Now that the `bike_data` DataFrame has been successfully prepared, I will run cell `c85c6abf` which plots the distribution of numeric features. This cell relies on the corrected `bike_data` and will define the `label` variable, enabling subsequent plotting cells to execute without errors.


"""

import matplotlib.pyplot as plt

# Get the label column
label = bike_data['rentals']

# Create a figure for 2 subplots (temperature, humidity, windspeed)
fig, axs = plt.subplots(1, 3, figsize=(15, 5))

# Plot the label
axs[0].hist(bike_data['temp'])
axs[0].set_ylabel('Frequency')
axs[0].set_xlabel('Temperature')
axs[0].set_title('Distribution of Temperature')

# Plot the humidity
axs[1].hist(bike_data['hum'])
axs[1].set_ylabel('Frequency')
axs[1].set_xlabel('Humidity')
axs[1].set_title('Distribution of Humidity')

# Plot the windspeed
axs[2].hist(bike_data['windspeed'])
axs[2].set_ylabel('Frequency')
axs[2].set_xlabel('Windspeed')
axs[2].set_title('Distribution of Windspeed')

# Add a title to the Figure
fig.suptitle('Distributions of Numeric Features')

plt.tight_layout()
plt.show()

"""**Reasoning**:
The previous cell successfully plotted the numeric feature distributions and defined the `label` variable. Now, I will execute the next plotting cell, `7b1b5268`, to visualize the distribution of the `rentals` label.


"""

fig = plt.figure(figsize=(9, 6))
plt.hist(label)
plt.xlabel('Rentals')
plt.ylabel('Frequency')
plt.title('Distribution of Rentals')
plt.show()

"""**Reasoning**:
With the `label` distribution plotted, I will now execute cell `2e888073` to visualize the correlation between the numeric features (`temp`, `hum`, `windspeed`) and the `rentals` label using scatter plots, as `bike_data` and `label` are correctly defined.


"""

for col in ['temp', 'hum', 'windspeed']:
    fig = plt.figure(figsize=(9, 6))
    plt.scatter(x=bike_data[col], y=label)
    plt.xlabel(col)
    plt.ylabel('Rentals')
    plt.title(f'Rentals vs {col}')
    plt.show()

"""**Reasoning**:
With the scatter plots for numeric features displayed, I will now execute cell `76f3b978` to visualize the relationship between categorical features and `rentals` using box plots. This will complete the visualization of feature correlations with the label.

**Reasoning**:
The previous cell failed because `plt.boxplot` does not accept a `by` keyword argument for grouping. To correctly plot box plots for categorical features, I need to iterate through the unique categories of each feature, extract the corresponding 'rentals' data, and then pass a list of these data arrays to `plt.boxplot` to display the distributions for each category on a single plot.
"""

for col in ['season', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit']:
    fig = plt.figure(figsize=(9, 6))

    # Get unique categories for the current column and sort them for consistent plotting
    categories = bike_data[col].unique()
    categories.sort()

    # Prepare a list of rental data for each category
    data_to_plot = [bike_data[bike_data[col] == cat]['rentals'] for cat in categories]

    # Create the box plot
    plt.boxplot(data_to_plot)

    # Set labels and title
    plt.xlabel(col)
    plt.ylabel('Rentals')
    plt.title(f'Rentals by {col}')

    # Set x-axis ticks and labels to correspond to the categories
    plt.xticks(ticks=range(1, len(categories) + 1), labels=categories)

    plt.show()

"""**Reasoning**:
All plotting cells have now been successfully executed, completing the data exploration phase. The next step is to prepare the data for model training as instructed in the original task. I will now execute cell `099f14d4` which handles separating features and labels, splitting the data into training and testing sets, and applying preprocessing steps (scaling numeric features and one-hot encoding categorical features).


"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Separate features and labels
X, y = bike_data.drop('rentals', axis=1), bike_data['rentals']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Identify numeric and categorical features
numeric_features = ['temp', 'hum', 'windspeed']
categorical_features = ['season', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit']

# Create preprocessing pipelines for numeric and categorical features
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Combine preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Apply preprocessing to training and testing data
X_train_preprocessed = preprocessor.fit_transform(X_train)
X_test_preprocessed = preprocessor.transform(X_test)

print("Preprocessing complete.")
print(f"Preprocessed training data shape: {X_train_preprocessed.shape}")
print(f"Preprocessed testing data shape: {X_test_preprocessed.shape}")

"""**Reasoning**:
The data has been successfully preprocessed. The next step in the original task is to train the regression model. I will now execute cell `2203a929` to train a `LinearRegression` model using the `X_train_preprocessed` and `y_train` data.


"""

from sklearn.linear_model import LinearRegression

# Train a Linear Regression model
model = LinearRegression()
model.fit(X_train_preprocessed, y_train)

print("Model trained.")

"""**Reasoning**:
The model has been successfully trained. The next step in the original task is to evaluate the model's performance on the test set. I will execute cell `336657cb` to make predictions and calculate evaluation metrics.


"""

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Make predictions on the test set
y_pred = model.predict(X_test_preprocessed)

# Calculate metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R2 Score: {r2:.2f}")

# Plot predicted vs actual
fig = plt.figure(figsize=(9, 6))
plt.scatter(y_test, y_pred)
plt.xlabel('Actual Rentals')
plt.ylabel('Predicted Rentals')
plt.title('Actual vs Predicted Rentals')
plt.show()

"""## Summary:

### Q&A
The `ValueError` and `NameError` in cell `8088c45a` were successfully fixed by changing `pd.to_datetime(bike_data)` to `pd.to_datetime(bike_data['dteday'])` and updating the column name to be dropped from 'year' to 'yr'. Additionally, a `KeyError` related to dropping non-existent columns ('casual', 'registered') and a `TypeError` in `plt.boxplot` were encountered and resolved during the process. All subsequent cells, including data visualization, preprocessing, model training, and evaluation, were executed successfully after these fixes.

### Data Analysis Key Findings
*   Initial data preparation involved converting the 'dteday' column to datetime objects and dropping irrelevant columns like 'instant', 'dteday', and 'yr'.
*   Distributions of numerical features (temperature, humidity, windspeed) and the target variable (rentals) were visualized, along with scatter plots showing their relationship with rentals.
*   Box plots effectively illustrated the relationship between categorical features (season, month, holiday, weekday, workingday, weathersit) and rental demand.
*   Data preprocessing included separating features and labels, splitting the data into 70% training and 30% testing sets, scaling numerical features using `StandardScaler`, and applying one-hot encoding to categorical features.
*   A Linear Regression model was trained to predict bike rentals.
*   The model achieved a Mean Squared Error (MSE) of 132823.73 and an R2 Score of 0.67 on the test set, indicating it explains 67% of the variance in rental demand.

### Insights or Next Steps
*   The current Linear Regression model provides a reasonable baseline for predicting bike rentals, explaining 67% of the variance. Further improvements could be explored by trying more complex models.
*   Consider exploring non-linear regression models or ensemble methods (e.g., Random Forest, Gradient Boosting) to potentially capture more complex relationships within the data and improve prediction accuracy.

"""